"""
Report generation for agentic tuning results.

This module generates markdown reports, ablation analyses, and convergence
plots from experiment logs.
"""

import logging
from typing import Dict, List, Optional

import pandas as pd

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generate reports and analyses of hyperparameter search results.

    Creates markdown reports with best configs, leaderboards, ablation
    analyses, and model family comparisons.

    Attributes:
        primary_metric: Name of primary metric being optimized
    """

    def __init__(self, primary_metric: str = "silhouette_score"):
        """Initialize report generator.

        Args:
            primary_metric: Name of primary metric.
        """
        self.primary_metric = primary_metric

    def generate(self, result) -> str:
        """Generate report from an AutoResearchResult.

        Args:
            result: AutoResearchResult instance

        Returns:
            Markdown report string
        """
        return self.generate_markdown(
            experiment_log=result.experiment_log,
            best_config=result.best_params,
        )

    def generate_markdown(
        self,
        experiment_log: pd.DataFrame,
        best_config: Dict,
    ) -> str:
        """Generate complete markdown report.

        Creates a comprehensive report with best configuration, leaderboard,
        ablation analysis, and comparisons.

        Args:
            experiment_log: DataFrame with experiment history.
            best_config: Best configuration found.

        Returns:
            Markdown report string.
        """
        sections = []

        # Header
        sections.append("# AutoResearch Report")
        sections.append("")
        sections.append("Generated by Karpathy Autoresearch Pattern")
        sections.append("")

        # Summary
        best_metric = experiment_log[self.primary_metric].max()
        n_trials = len(experiment_log)
        n_improvements = (
            experiment_log[self.primary_metric].diff().gt(0).sum()
        )

        sections.append("## Summary")
        sections.append("")
        sections.append(
            f"- **Best {self.primary_metric}:** {best_metric:.4f}"
        )
        sections.append(f"- **Total Trials:** {n_trials}")
        sections.append(f"- **Improvements:** {int(n_improvements)}")
        sections.append("")

        # Best Configuration
        sections.append("## Best Configuration")
        sections.append("")
        sections.append(self._format_config(best_config))
        sections.append("")

        # Leaderboard
        leaderboard = self._generate_leaderboard(experiment_log)
        sections.append("## Top 10 Trials")
        sections.append("")
        sections.append(leaderboard)
        sections.append("")

        # Convergence Analysis
        convergence = self._generate_convergence_analysis(experiment_log)
        sections.append("## Convergence Analysis")
        sections.append("")
        sections.append(convergence)
        sections.append("")

        # Ablation Analysis
        ablation = self._generate_ablation_table(experiment_log)
        sections.append("## Hyperparameter Importance (Ablation Analysis)")
        sections.append("")
        sections.append(ablation)
        sections.append("")

        # Model Family Comparison
        comparison = self._compare_model_families(experiment_log)
        if comparison:
            sections.append("## Model Family Comparison")
            sections.append("")
            sections.append(comparison)
            sections.append("")

        # Recommendations
        sections.append("## Recommendations")
        sections.append("")
        sections.append(self._generate_recommendations(experiment_log, best_config))
        sections.append("")

        return "\n".join(sections)

    def _format_config(self, config: Dict) -> str:
        """Format configuration as markdown.

        Args:
            config: Configuration dictionary.

        Returns:
            Markdown formatted config.
        """
        lines = ["```json"]
        for key, value in sorted(config.items()):
            if isinstance(value, float):
                lines.append(f'  "{key}": {value:.6e},')
            else:
                lines.append(f'  "{key}": {repr(value)},')
        lines.append("```")
        return "\n".join(lines)

    def _generate_leaderboard(
        self,
        experiment_log: pd.DataFrame,
        top_n: int = 10,
    ) -> str:
        """Generate top N trials leaderboard.

        Args:
            experiment_log: Experiment history.
            top_n: Number of top trials to show.

        Returns:
            Markdown table of leaderboard.
        """
        top = experiment_log.nlargest(top_n, self.primary_metric).copy()

        # Create markdown table
        lines = [
            "| Rank | Trial | Metric | Model Type | Learning Rate | Layers |",
            "|------|-------|--------|------------|----------------|--------|",
        ]

        for rank, (_, row) in enumerate(top.iterrows(), 1):
            metric = row[self.primary_metric]
            model_type = row.get("config_model_type", "N/A")
            lr = row.get("config_learning_rate", "N/A")
            layers = row.get("config_n_layers", "N/A")

            if isinstance(lr, float):
                lr = f"{lr:.2e}"

            lines.append(
                f"| {rank} | {int(row.get('trial_id', rank))} | {metric:.4f} | "
                f"{model_type} | {lr} | {layers} |"
            )

        return "\n".join(lines)

    def _generate_convergence_analysis(self, experiment_log: pd.DataFrame) -> str:
        """Generate convergence analysis text.

        Args:
            experiment_log: Experiment history.

        Returns:
            Markdown text describing convergence.
        """
        metric_vals = experiment_log[self.primary_metric]
        best_vals = metric_vals.expanding().max()

        convergence_rate = (
            best_vals.diff().abs().mean() / metric_vals.std()
            if metric_vals.std() > 0 else 0
        )

        lines = [
            f"**Metric Statistics:**",
            f"- Mean: {metric_vals.mean():.4f}",
            f"- Std Dev: {metric_vals.std():.4f}",
            f"- Min: {metric_vals.min():.4f}",
            f"- Max: {metric_vals.max():.4f}",
            f"- Convergence Rate: {convergence_rate:.6f}",
        ]

        # Detect if converged
        recent = metric_vals.tail(int(len(metric_vals) * 0.2))
        best_recent = best_vals.tail(int(len(best_vals) * 0.2)).max()
        best_overall = best_vals.max()

        if abs(best_recent - best_overall) < metric_vals.std() * 0.1:
            lines.append(
                "\n⚠️ **Convergence Status:** Likely converged. "
                "Recent improvements are marginal."
            )
        else:
            lines.append(
                "\n✓ **Convergence Status:** Still improving. "
                "Consider running more trials."
            )

        return "\n".join(lines)

    def _generate_ablation_table(self, experiment_log: pd.DataFrame) -> str:
        """Generate ablation table showing parameter importance.

        Args:
            experiment_log: Experiment history.

        Returns:
            Markdown table of parameter importance.
        """
        # Extract config columns
        config_cols = [
            col for col in experiment_log.columns
            if col.startswith("config_")
        ]

        # Calculate importance as variance correlation
        importance = {}
        for col in config_cols:
            param_name = col.replace("config_", "")

            # For numeric columns, use correlation
            if pd.api.types.is_numeric_dtype(experiment_log[col]):
                try:
                    corr = experiment_log[col].corr(experiment_log[self.primary_metric])
                    importance[param_name] = abs(corr)
                except Exception:
                    importance[param_name] = 0.0
            else:
                # For categorical, use variance contribution
                importance[param_name] = 0.0

        # Sort by importance
        sorted_importance = sorted(
            importance.items(),
            key=lambda x: x[1],
            reverse=True
        )

        # Create markdown table
        lines = [
            "| Parameter | Importance |",
            "|-----------|------------|",
        ]

        for param, imp_score in sorted_importance[:15]:  # Top 15
            bar_width = int(imp_score * 30)
            bar = "█" * bar_width + "░" * (30 - bar_width)
            lines.append(
                f"| {param} | {bar} {imp_score:.3f} |"
            )

        return "\n".join(lines)

    def _compare_model_families(self, experiment_log: pd.DataFrame) -> Optional[str]:
        """Compare different model families.

        Args:
            experiment_log: Experiment history.

        Returns:
            Markdown comparison or None if insufficient data.
        """
        if "config_model_type" not in experiment_log.columns:
            return None

        model_types = experiment_log["config_model_type"].unique()
        if len(model_types) < 2:
            return None

        lines = [
            "| Model Type | Count | Mean Metric | Best Metric |",
            "|------------|-------|-------------|-------------|",
        ]

        for model_type in sorted(model_types):
            subset = experiment_log[
                experiment_log["config_model_type"] == model_type
            ]
            count = len(subset)
            mean_metric = subset[self.primary_metric].mean()
            best_metric = subset[self.primary_metric].max()

            lines.append(
                f"| {model_type} | {count} | {mean_metric:.4f} | {best_metric:.4f} |"
            )

        return "\n".join(lines)

    def _generate_recommendations(
        self,
        experiment_log: pd.DataFrame,
        best_config: Dict,
    ) -> str:
        """Generate actionable recommendations.

        Args:
            experiment_log: Experiment history.
            best_config: Best configuration.

        Returns:
            Markdown recommendations.
        """
        lines = []

        # Check if search is exhaustive
        best_metric = experiment_log[self.primary_metric].max()
        mean_metric = experiment_log[self.primary_metric].mean()
        gap = best_metric - mean_metric

        if gap < 0.01:
            lines.append(
                "1. **Search Saturation:** Small gap between best and "
                "average suggests search space may be saturated. "
                "Consider expanding parameter bounds."
            )
        else:
            lines.append(
                f"1. **Parameter Optimization:** Found {gap:.4f} improvement "
                "over mean. Continue optimizing or expand search."
            )

        # Check convergence
        recent = experiment_log[self.primary_metric].tail(10)
        if recent.max() == experiment_log[self.primary_metric].max():
            lines.append(
                "2. **Early Improvement:** Best result in recent trials. "
                "Increase search budget or reduce patience for early stopping."
            )
        else:
            lines.append(
                "2. **Convergence Achieved:** No recent improvements. "
                "Search strategy appears well-tuned."
            )

        # Recommend next steps
        lines.append(
            "3. **Next Steps:**"
        )
        lines.append(
            "   - Save best configuration to pipeline"
        )
        lines.append(
            "   - Train final model with best config on full data"
        )
        lines.append(
            "   - Evaluate on held-out test set"
        )
        lines.append(
            "   - Compare against baseline approaches"
        )

        return "\n".join(lines)

    def generate_convergence_data(
        self,
        experiment_log: pd.DataFrame,
    ) -> Dict:
        """Generate data for convergence plot.

        Args:
            experiment_log: Experiment history.

        Returns:
            Dictionary with trial numbers and metric values.
        """
        return {
            "trials": experiment_log.index.tolist(),
            "metrics": experiment_log[self.primary_metric].tolist(),
            "best_so_far": experiment_log[self.primary_metric].expanding().max().tolist(),
        }
